#
# SPDX-License-Identifier: GPL-2.0-only
#

SDIR_SUBMODULES := $(BASE_DIR)/submodules
DEP_DIRS += $(BASE_DEP_DIR)/submodules

include $(SDIR_SUBMODULES)/ammarfaizi2/Makefile
include $(SDIR_SUBMODULES)/tdlib/Makefile
